config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

    resources :users
    resources :activities
    resources :issues do
      member do
          put 'upvote', to: "issues#upvote"
          put 'downvote', to: "issues#downvote"
      end
      resources :comments do
        member do
          put 'upvote', to: "comments#upvote"
          put 'downvote', to: "comments#downvote"
        end
      end
    end

  root 'issues#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Common
  # tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :issue

  #add helper to model
  acts_as_votable

  def votes
    self.get_upvotes.size - self.get_downvotes.size
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_issue, only: [:new, :create, :index, :upvote, :downvote]
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def upvote
    @comment.upvote_by current_user
    redirect_to issue_path(@issue), notice: 'Comment is upvoted'
  end

  def downvote
    @comment.downvote_by current_user
    redirect_to issue_path(@issue), notice: 'Comment is downvoted'
  end

  def create
    @comment = @issue.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        @comment.create_activity :create, owner: current_user
        format.html { redirect_to issue_path(@issue), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { redirect_to issue_path(@issue), alert: "Comments can't be blank" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to issue_path(@issue), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    # @comment.create_activity :destroy, owner: current_user
    respond_to do |format|
      format.html { redirect_to issue_path(@comment.issue), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_issue
      @issue = Issue.find(params[:issue_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :body, :issue_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= simple_form_for [@issue, @comment] do |f|

  .input-group
    = f.hidden_field :user_id, value: current_user.id
  .input-group
    / = f.label :body
    = f.cktext_area :body
  .input-group
    = f.hidden_field :issue_id
  %br
    = f.button :submit, 'Save', class: "btn btn-primary"
  %br
  %br

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th User
    %th Body
    %th Issue
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.user_id
      %td= comment.body
      %td= comment.issue_id
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_issue_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b User:
  = @comment.user_id
%p
  %b Body:
  = @comment.body
%p
  %b Issue:
  = @comment.issue_id

= link_to 'Edit', edit_comment_path(@comment)