config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

    resources :users
    resources :activities
    resources :issues do
      member do
          put 'upvote', to: "issues#upvote"
          put 'downvote', to: "issues#downvote"
      end
      resources :comments do
        member do
          put 'upvote', to: "comments#upvote"
          put 'downvote', to: "comments#downvote"
        end
      end
    end

  root 'issues#index'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include PublicActivity::Model
  # tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user
  has_many :comments

  validates :title, :description, :assignee, :kind, :priority, presence: true

  KIND = %w(bug enhancement proposal task)
  PRIORITY = %w(trivial minor major critical blocker)
  STATUS = %w(new open resolved closed pending duplicate invalid)
  LOCATION = %w(dashboard contacts tasks messages projects)

  after_create :send_notification

  #add helper to model
  acts_as_votable

  def send_notification
    IssueMailer.new_issue(self).deliver
  end

  def votes
    self.get_upvotes.size - self.get_downvotes.size
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.order("created_at DESC")
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @comments = @issue.comments.all
    @comment = @issue.comments.build
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  def upvote
    @issue.upvote_by current_user
    redirect_to issue_path(@issue), notice: 'Issue is upvoted'
  end

  def downvote
    @issue.downvote_by current_user
    redirect_to issue_path(@issue), notice: 'Issue is downvoted'
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = current_user.issues.new(issue_params)

    respond_to do |format|
      if @issue.save
        @issue.create_activity :create, owner: current_user
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { redirect_to new_issue_path, alert: 'Please fill in all the required field marked with *' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    # @issue.create_activity :destroy, owner: current_user
    respond_to do |format|
      format.html { redirect_to @issue, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :assignee, :kind, :priority, :location, :status)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.haml
= simple_form_for [@user,@issue], html: { multipart:true } do |f|
  - if @issue.errors.any?
    #errors
      %p
        = @issue.errors.count
        Prevented your issue from saving
      %ul
        - @issue.errors.full_messages.each do |msg|
          %li= msg

  .input-group
    = f.input :title, input_html: { class: 'form-control' }
  %br
  .input-group
    = f.label :description, class: 'required', input_html: { class: 'form-control' }
    = f.cktext_area :description, rows: 10
  %br
  .input-group
    = f.label :assignee, class: 'required'
    %br
    / = f.collection_select :assignee, User.all, :id, :name, {}, {:multiple => true}
    = f.collection_select :assignee, User.all, :id, :name, {:multiple => :true}
  %br
  .input-group
    = f.label :kind, class: 'required'
    = f.select :kind, Issue::KIND
  %br
  .input-group
    = f.label :priority, class: 'required'
    = f.select :priority, Issue::PRIORITY
  %br
  .input-group
    = f.label :location, class: 'required'
    = f.select :location, Issue::LOCATION
  %br
  .input-group
    = f.label :status
    = f.select :status, Issue::STATUS
  %br
  = f.button :submit, 'Save', class: "btn btn-success inline pull-left"

app/views/issues/edit.html.haml
.panel.panel-default.col-lg-8
  .panel-heading.clearfix
    %h1 Editing issue

    = render 'form'
    / = link_to 'Show', @issue, class: "btn btn-primary"
    &nbsp;&nbsp;
    = link_to 'Back', issues_path, class: "btn btn-primary"

app/views/issues/index.html.haml
%h1
  Issues

  = link_to '<i class="glyphicon, glyphicon-plus"></i> New Issue'.html_safe, new_issue_path, class: 'btn btn-default'

%table#table_beautify.display
  %thead
    %tr
      %th Index
      %th Title
      %th Kind
      %th Priority
      %th Assignor
      %th Status
      %th Assignee
      %th Votes
      %th Created at
      %th
      %th
      %th

  %tbody
    - @issues.each do |issue|
      %tr
        %td ##{issue.id}
        %td= issue.title
        %td= issue.kind
        %td= issue.priority
        %td= User.find_by_id(issue.user_id).name
        %td
          %span.label.label-primary= issue.status.upcase
        %td= User.find_by_id(issue.assignee).name
        %td= issue.votes
        %td= issue.created_at.strftime("%d %b. %Y %H:%M")
        %td= link_to 'Show', issue
        %td= link_to 'Edit', edit_issue_path(issue)
        %td= link_to 'Destroy', issue, :method => :delete, :data => { :confirm => 'Are you sure?' }


:coffeescript
  $(document).ready ->
    $("#table_beautify").DataTable()
    return

app/views/issues/new.html.haml
.panel.panel-default.col-lg-8
  .panel-heading.clearfix
    %h1 New issue

    = render 'form'
    &nbsp;&nbsp;
    = link_to 'Back', issues_path, class: "btn btn-primary"

app/views/issues/show.html.haml
.panel.panel-default.col-lg-8
  .panel-heading.clearfix
    %h3.panel-title
      %strong
        = @issue.title.html_safe.capitalize
    .pull-right
      = link_to 'Edit', edit_issue_path(@issue), class: "btn btn-default btn-sm"
      = link_to 'Back', issues_path, class: "btn btn-default btn-sm"
      .pull-right{:style => "margin:80px 0px 20px -40px"}
        .pull-up
          = link_to upvote_issue_path(@issue), method: :put, class: "btn btn-default btn-sm" do
            %span.glyphicon.glyphicon-arrow-up
        %span.badge{:style => "margin:5px 0px 5px 7px"}
          = @issue.votes
        .pull-down
          = link_to downvote_issue_path(@issue), method: :put, class: "btn btn-default btn-sm" do
            %span.glyphicon.glyphicon-arrow-down
    .panel-body
      %div
        / = image_tag @issue.image.url(:large)
      %div
        %strong Description:
        = @issue.description.html_safe
      %div
        %strong Kind:
        = @issue.kind
      %div
        %strong Priority:
        = @issue.priority
      %div
        %strong Assignor:
        = User.find_by_id(@issue.user_id).name
      %div
        %strong Assignee:
        = User.find_by_id(@issue.assignee).name

  %br/
  %br/
  %h4 Comments
  - @comments.each do |comment|
    %div
      .panel.panel-default{:style => "width:17.4cm"}
        .panel-heading.clearfix
          %h3.panel-title.pull-left
            %strong
              = User.find_by_id(comment.user_id).name
            commented :
          .pull-right
            = link_to upvote_issue_comment_path(@issue, comment), method: :put, class: "btn btn-default btn-sm" do
              %span.glyphicon.glyphicon-arrow-up
            %span.badge
              = comment.votes
            = link_to downvote_issue_comment_path(@issue, comment), method: :put, class: "btn btn-default btn-sm" do
              %span.glyphicon.glyphicon-arrow-down
        .panel-body
          .col-lg-9
            = comment.body.html_safe
          .pull-right
            / = link_to edit_issue_comment_path(@issue,comment), class: "btn btn-default btn-sm" do
            /   Edit
            = link_to 'Delete', issue_comment_path(@issue,comment), method: :delete, class: "btn btn-default btn-sm", data: { confirm: 'Are you sure?' }
      %p

  = render 'comments/form'